// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZNR7qQom4cNzdx4j8RpP39N_z8yepOWM',
    appId: '1:700985298955:web:e7ad4ebf5f7fdcab42770e',
    messagingSenderId: '700985298955',
    projectId: 'birthday-scheduler-4-activity',
    authDomain: 'birthday-scheduler-4-activity.firebaseapp.com',
    storageBucket: 'birthday-scheduler-4-activity.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-QfCw08m0KtAyDZTsz_WhWpHsei2P5vc',
    appId: '1:700985298955:android:8d26f28d11b0727342770e',
    messagingSenderId: '700985298955',
    projectId: 'birthday-scheduler-4-activity',
    storageBucket: 'birthday-scheduler-4-activity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1wy446dUWf_r9i7M6_uCIrgzAGtitnyE',
    appId: '1:700985298955:ios:6c0a07e0cb5287c142770e',
    messagingSenderId: '700985298955',
    projectId: 'birthday-scheduler-4-activity',
    storageBucket: 'birthday-scheduler-4-activity.appspot.com',
    iosClientId:
        '700985298955-93u6nvfk2an2eqa05v7gnoeqcftsfs3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.birthdayScheduler',
  );
}
